### ISSUE TITLE
html-webpack-plugin v1.4.0 causes strange error during webpack build

### ISSUE THREAD

**Issue by why-jay** [chcokr/webapp-build#5]
When I build CWB with v1.4.0 and builds a project with that CJB, I get the following error message in the webpack build stats output, and don't get any bundles generated (probably because of NoErrorsPlugin).

```
ERROR in undefined
```

(not very helpful lol)

However when I switch to v1.3.0 or 1.2.0 things seem to work fine. I have confirmed this problem narrows down to the scope of html-webpack-plugin.

I'll investigate further, and if this is an upstream issue within html-webpack-plugin, I'll create an issue there.

**Comment by mateatslc** [comment]
same here, except my bundles still being generated fine

**Comment by why-jay** [comment]
Do you know if this issue is being tracked at ampedandwired/html-webpack-plugin at all?

**Comment by mateatslc** [comment]
I can't find it reported over there.

**Comment by mateatslc** [comment]
came across some relevant info here: 
http://stackoverflow.com/questions/30423710/webpack-verbose-error-message

specifically:
https://github.com/ampedandwired/html-webpack-plugin/issues/50

**Comment by why-jay** [comment]
I no longer use this plugin, closing
